# 调用GPU计算

In [1]:
import torch
from torch import nn

torch.cuda.is_available()

True

In [2]:
torch.cuda.device_count()

1

In [4]:
torch.cuda.current_device()
torch.cuda.get_device_name(0)

'GeForce RTX 2070'

In [5]:
x = torch.tensor([1, 2, 3])
x

tensor([1, 2, 3])

# 使用GPU计算

In [7]:
x = x.cuda(0)
x

tensor([1, 2, 3], device='cuda:0')

In [8]:
x.device

device(type='cuda', index=0)

In [9]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

x = torch.tensor([1, 2, 3], device=device)
# or
x = torch.tensor([1, 2, 3]).to(device)
x

tensor([1, 2, 3], device='cuda:0')

In [10]:
y = x ** 2
y

tensor([1, 4, 9], device='cuda:0')

# 模型的GPU计算：保证所有的模型和参数都在GPU上，才能利用GPU的高执行效率

In [11]:
net = nn.Linear(3, 1)
list(net.parameters())[0].device

device(type='cpu')

In [12]:
net.cuda()
list(net.parameters())[0].device

device(type='cuda', index=0)