# 数据操作

In [2]:
import torch

x = torch.empty(5,3)
print(x)

tensor([[3.2483e+33, 1.9690e-19, 6.8589e+22],
        [1.3340e+31, 1.1708e-19, 7.2128e+22],
        [9.2216e+29, 7.5546e+31, 1.6932e+22],
        [3.0728e+32, 2.9514e+29, 2.8940e+12],
        [7.5338e+28, 1.8037e+28, 3.4740e-12]])


In [4]:
x = torch.rand(5,3)
print(x)

tensor([[0.7210, 0.6698, 0.0956],
        [0.9519, 0.5586, 0.4831],
        [0.3538, 0.7904, 0.8360],
        [0.8041, 0.4748, 0.0792],
        [0.7639, 0.2466, 0.8537]])


In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [9]:
x = torch.tensor([5.5, 3], dtype=torch.float)
print(x)

tensor([5.5000, 3.0000])


In [10]:
print(x.size())

torch.Size([2])


In [11]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x.size())

torch.Size([5, 3])


In [13]:
print(x.shape)

torch.Size([5, 3])


# 算术计算

In [15]:
y=torch.rand(5,3)
x=torch.rand(5,3)
print(x)
print(y)
print(x+y)

tensor([[0.7989, 0.0728, 0.0426],
        [0.3514, 0.7241, 0.4024],
        [0.0189, 0.1952, 0.6769],
        [0.4554, 0.3101, 0.3664],
        [0.4188, 0.1138, 0.8180]])
tensor([[0.0757, 0.1290, 0.2807],
        [0.7650, 0.6708, 0.4999],
        [0.9181, 0.4483, 0.4582],
        [0.7988, 0.8737, 0.5015],
        [0.7780, 0.6916, 0.9295]])
tensor([[0.8746, 0.2017, 0.3233],
        [1.1164, 1.3949, 0.9023],
        [0.9369, 0.6435, 1.1350],
        [1.2542, 1.1838, 0.8679],
        [1.1968, 0.8054, 1.7476]])


In [16]:
y = x[0, :]
print(y)

tensor([0.7989, 0.0728, 0.0426])


In [19]:
y += 1
print(y)
print(x)

tensor([3.7989, 3.0728, 3.0426])
tensor([[0.7989, 0.0728, 0.0426],
        [0.3514, 0.7241, 0.4024],
        [0.0189, 0.1952, 0.6769],
        [0.4554, 0.3101, 0.3664],
        [0.4188, 0.1138, 0.8180]])


In [20]:
print(y.size())
print(x.size())

torch.Size([3])
torch.Size([5, 3])


In [21]:
y = x.view(15)
print(y)
print(y.size())

tensor([0.7989, 0.0728, 0.0426, 0.3514, 0.7241, 0.4024, 0.0189, 0.1952, 0.6769,
        0.4554, 0.3101, 0.3664, 0.4188, 0.1138, 0.8180])
torch.Size([15])


In [24]:
z=x.view(-1,3)
print(z)
print(z.size())

tensor([[0.7989, 0.0728, 0.0426],
        [0.3514, 0.7241, 0.4024],
        [0.0189, 0.1952, 0.6769],
        [0.4554, 0.3101, 0.3664],
        [0.4188, 0.1138, 0.8180]])
torch.Size([5, 3])


In [25]:
z = z + 1
print(z)
print(x)

tensor([[1.7989, 1.0728, 1.0426],
        [1.3514, 1.7241, 1.4024],
        [1.0189, 1.1952, 1.6769],
        [1.4554, 1.3101, 1.3664],
        [1.4188, 1.1138, 1.8180]])
tensor([[0.7989, 0.0728, 0.0426],
        [0.3514, 0.7241, 0.4024],
        [0.0189, 0.1952, 0.6769],
        [0.4554, 0.3101, 0.3664],
        [0.4188, 0.1138, 0.8180]])


In [26]:
print(z.t())

tensor([[1.7989, 1.3514, 1.0189, 1.4554, 1.4188],
        [1.0728, 1.7241, 1.1952, 1.3101, 1.1138],
        [1.0426, 1.4024, 1.6769, 1.3664, 1.8180]])


# 矩阵运算中的广播效应

In [27]:
x = torch.arange(1,3).view(1,2)
print(x)
y = torch.arange(1,4).view(3,1)
print(y)
print(x+y)

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


# GPU测试

In [28]:
# 以下代码只有在PyTorch GPU版本上才会执行
if torch.cuda.is_available():
    device = torch.device("cuda")          # GPU
    y = torch.ones_like(x, device=device)  # 直接创建一个在GPU上的Tensor
    x = x.to(device)                       # 等价于 .to("cuda")
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # to()还可以同时更改数据类型

tensor([[2, 3]], device='cuda:0')
tensor([[2., 3.]], dtype=torch.float64)
